Repository marshalmiller/linkrot, pull requests merged in 2022-10, with the labels that each got.

#144 Resolved Add DOIs to References Summary #128
  linkrot/cli.py
Labels: hacktoberfest, hacktoberfest-accepted

#146 Remove numpy import
  linkrot/cli.py
Labels: hacktoberfest

#147 Fix the page number error, in the link checker
  linkrot/backends.py
Labels: hacktoberfest

#145 Add Link Check Results to CLI Output #120
  linkrot/cli.py
  linkrot/colorprint.py
  linkrot/downloader.py
Labels: hacktoberfest

#149 Migrating from setup.py to pyproject.toml
  .github/workflows/lint-and-test.yml
  Makefile
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  setup.cfg
  setup.py
Labels: enhancement, hacktoberfest, python

#156 Upgrade to PyProject
  .github/workflows/lint-and-test.yml
  Makefile
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  setup.cfg
  setup.py
Labels: enhancement, dependencies, hacktoberfest, python, hacktoberfest-accepted

#158 add missing dependencies
  pyproject.toml
Labels: dependencies, hacktoberfest, hacktoberfest-accepted

#157 add missing cli entry point
  pyproject.toml
Labels: bug, hacktoberfest, python, hacktoberfest-accepted

#159 handle UnicodeDecode exception
  linkrot/backends.py
Labels: bug, hacktoberfest, python, hacktoberfest-accepted

#161 Add test cases for detecting embedded URLs
  tests/pdfs/embedded_link_image.pdf
  tests/pdfs/embedded_link_testcase.pdf
  tests/test_linkrot.py
Labels: enhancement, hacktoberfest, python, hacktoberfest-accepted
